# i took this from vencord sync to codeberg workflow lol

name: Sync to Codeberg
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # runs every 6h

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: "git@codeberg.org:ChipOverThere/WordsCheck.git"
          ssh_private_key: ${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}
